### ISSUE TITLE
unit test fails for main_test.rb (test_simple_equals)

### ISSUE THREAD

**Issue by orthogonous** [matsadler/nagios_config#1]
$ ruby main_test.rb 
Loaded suite main_test
Started
............E
Finished in 0.001737 seconds.

  1) Error:
test_simple_equals(MainTest):
ArgumentError: odd number of arguments for Hash
    /home/lachlan/nagios_config/lib/nagios_config/main.rb:6:in `[]'
    /home/lachlan/nagios_config/lib/nagios_config/main.rb:6:in`initialize'
    main_test.rb:80:in `new'
    main_test.rb:80:in`test_simple_equals'

13 tests, 32 assertions, 0 failures, 1 errors, 0 skips

Test run options: --seed 10505
$ 

I'm working on fixing this ( just need to learn how your code works etc )

**Comment by orthogonous** [comment]
I've added a pull request but I can't work out how to link it to this issue. ( I'm new here )
